// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWL-CDs1bM7giY0KkLF_ahB_Uvc-TvTbY',
    appId: '1:403399282415:web:a0ee7c0c922244367c551a',
    messagingSenderId: '403399282415',
    projectId: 'chat-app-78bba',
    authDomain: 'chat-app-78bba.firebaseapp.com',
    storageBucket: 'chat-app-78bba.appspot.com',
    measurementId: 'G-D3L7VTL7HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByTNpQe3IY3NDX6GNqxPqEM6k4UvDkIcA',
    appId: '1:403399282415:android:935b6ab33b7120287c551a',
    messagingSenderId: '403399282415',
    projectId: 'chat-app-78bba',
    storageBucket: 'chat-app-78bba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPQZBeoFBW-wHfZ728mGIBVQ4OHM71YAY',
    appId: '1:403399282415:ios:ae0e0a4c79dfcfc37c551a',
    messagingSenderId: '403399282415',
    projectId: 'chat-app-78bba',
    storageBucket: 'chat-app-78bba.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPQZBeoFBW-wHfZ728mGIBVQ4OHM71YAY',
    appId: '1:403399282415:ios:c27f824a10a46c7a7c551a',
    messagingSenderId: '403399282415',
    projectId: 'chat-app-78bba',
    storageBucket: 'chat-app-78bba.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
